export class ArgumentError extends Error {}
export class KeyNotFoundError extends Error {}
export class NotSupportedError extends Error {}
export class NotFoundError extends Error {}
export class QuotaExceededError extends Error {}
export class KeyAlreadyExistsError extends Error {}
export class DecompressionError extends Error {}
export class InvalidJsonError extends Error {}
export class UnusedStorageError extends Error {}
