@startuml layeredArchitecture
title レイヤ構成図 : GameDiaryの依存関係


package UI{
  interface UseCaseIntaerface
  [React Components] --> UseCaseIntaerface
  [Presentation Logic (Custom Hooks / Context)] --> UseCaseIntaerface
}
package Application{
  UseCaseIntaerface <|-- [Diary UseCases]
  [Diary UseCases]
  interface StorageInterface
  [Diary UseCases] --> StorageInterface
}
package Domain {
  [Domain Model]
}

package Storage{
  StorageInterface<|--[StorageService]
  StorageService-->[LocalStorage]
  [LocalStorage]
}

Application --> Domain
@enduml