version: '3'
services:
  plantuml-server:
    image: plantuml/plantuml-server
    restart: always
    ports:
      - "8080"
  app:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ../:/app
    environment:
      - plantuml_HOST=plantuml-server
      - plantuml_PORT=8080
    tty: true
